### ISSUE TITLE
싸이월드 중간 section 만들기

### ISSUE THREAD

**Issue by doa0819** [hellooo1321321/cyworldPractice#2]
### (페이지)
- [] updated news 창 이용해서 각자의 팀원들의 깃허브로 연동
- [] miniroom 창 꾸미기 사진 넣기
-  [] friends say 이용해서 label 이용 input 이용 넣고 싶은 내용 전달, button 이용에 내용 넣기

**Comment by YoonJae00** [comment]
잘했어요!!!
